### ISSUE TITLE
Sub partials can not be used in static and dynamic hbs at the same time

### ISSUE THREAD

**Issue by dweiger** [biotope/biotope-build#34] opened 2018-02-09 07:55 UTC
https://github.com/frontend-framework/build-framework/blob/7b32bf362849d7c003f904fb64604d4f7b02532b/tasks/handlebars.js#L33

In static rendereing the path name is always full pathname including {{include 'components/partial'}}
In dynamic hbs only basname is nedded {{> partial }}. Thus it appears that it is not possible to use dynamic and static rendering at the same time.

Probably this issue would be solved by adapting the path in the code linked to this issue.

**Comment by timomayer** [comment] 2018-03-10 15:20
Duplicate of: https://github.com/biotope/biotope-build/issues/3

**Closed by timomayer** 2018-03-10 15:20 UTC
